### PR TITLE
Fix Guzzle conflicts in Moodle 4.2

### LINKED ISSUE #56: 4.2 dev upgrade fails
Upgrade from 3.11 -> 4.2dev

```
Exception - Undefined constant GuzzleHttp\Client::VERSION

[More information about this error](http://docs.moodle.org/311/en/error/moodle/generalexceptionmessage)

Debug info:
Error code: generalexceptionmessage×Dismiss this notification
Stack trace:
line 136 of /local/aws/sdk/GuzzleHttp/functions.php: Error thrown
line 40 of /local/aws/sdk/Aws/Handler/GuzzleV6/GuzzleHandler.php: call to GuzzleHttp\default_user_agent()
line 87 of /local/aws/sdk/Aws/WrappedHttpHandler.php: call to Aws\Handler\GuzzleV6\GuzzleHandler->__invoke()
line 126 of /local/aws/sdk/Aws/ClientSideMonitoring/AbstractMonitoringMiddleware.php: call to Aws\WrappedHttpHandler->__invoke()
line 43 of /local/aws/sdk/Aws/S3/PermanentRedirectMiddleware.php: call to Aws\ClientSideMonitoring\AbstractMonitoringMiddleware->__invoke()
line 41 of /local/aws/sdk/Aws/S3/PutObjectUrlMiddleware.php: call to Aws\S3\PermanentRedirectMiddleware->__invoke()
line 126 of /local/aws/sdk/Aws/Middleware.php: call to Aws\S3\PutObjectUrlMiddleware->__invoke()
line 41 of /lib/guzzlehttp/promises/src/FulfilledPromise.php: call to Aws\Middleware::Aws\{closure}()
line 48 of /lib/guzzlehttp/promises/src/TaskQueue.php: call to GuzzleHttp\Promise\FulfilledPromise::GuzzleHttp\Promise\{closure}()
line 248 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\TaskQueue->run()
line 224 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\Promise->invokeWaitFn()
line 269 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\Promise->waitIfPending()
line 226 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\Promise->invokeWaitList()
line 62 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\Promise->waitIfPending()
line 58 of /local/aws/sdk/Aws/AwsClientTrait.php: call to GuzzleHttp\Promise\Promise->wait()
line 693 of /local/aws/sdk/Aws/S3/StreamWrapper.php: call to Aws\AwsClient->execute()
line 152 of /local/aws/sdk/Aws/S3/StreamWrapper.php: call to Aws\S3\StreamWrapper->openReadStream()
line 918 of /local/aws/sdk/Aws/S3/StreamWrapper.php: call to Aws\S3\StreamWrapper->Aws\S3\{closure}()
line 156 of /local/aws/sdk/Aws/S3/StreamWrapper.php: call to Aws\S3\StreamWrapper->boolCall()
line ? of unknownfile: call to Aws\S3\StreamWrapper->stream_open()
line 434 of /admin/tool/objectfs/classes/local/store/object_file_system.php: call to file_get_contents()
line 453 of /lib/filestorage/stored_file.php: call to tool_objectfs\local\store\object_file_system->get_content()
line 165 of /lib/db/upgrade.php: call to stored_file->get_content()
line 1890 of /lib/upgradelib.php: call to xmldb_main_upgrade()
line 527 of /admin/index.php: call to upgrade_core()
```

### PR DESCRIPTION
**Pull request by sarahjcotton**
Fixes #56

### CODE REVIEW

**Comment by sarahjcotton** [comment]
Not sure why the master branch is failing with the error `Not enough arguments (missing: "plugin").`

**Comment by dmitriim** [comment]
hey @sarahjcotton Thanks for working on this! 

There is an error in install Moodle step. Not your fault. Probably CI worflows should be updated and DB version bumped. 

```
  RUN  php -d log_errors=1 -d error_log=NULL /home/runner/work/moodle-local_aws/moodle-local_aws/moodle/admin/tool/phpunit/cli/util.php --install
    OUT  == Environment ==
    OUT  !! database postgres (12.14 (Debian 12.14-1.pgdg110+1)) !!
    OUT  [System] version 13 is required and you are running 12.14 - 
    OUT  
    OUT  
    RES  1 Command did not run successfully
  
  In Execute.php line 180:
                                                                                 
    [Symfony\Component\Process\Exception\ProcessFailedException]                 
    The command "php -d log_errors=1 -d error_log=NULL /home/runner/work/moodle  
    -local_aws/moodle-local_aws/moodle/admin/tool/phpunit/cli/util.php --instal  
    l" failed.                                                                   
                                                                                 
    Exit Code: 1(General error)                                                  
                                                                                 
    Working directory: /home/runner/work/moodle-local_aws/moodle-local_aws       
                                                                                 
    Output:                                                                      
    ================                                                             
    == Environment ==                                                            
    !! database postgres (12.14 (Debian 12.14-1.pgdg110+1)) !!                   
    [System] version 13 is required and you are running 12.14
```

**Comment by sarahjcotton** [comment]
Thanks for fixing the workflow @keevan - Do you know when this PR is likely to get merged? We're in the middle of doing some upgrades which this is having an impact on. Many thanks.

**Comment by dmitriim** [comment]
@sarahjcotton looks like this ready to be merged. Just wondering if there is a Guzzle version difference between core and this plugin?

**Comment by sarahjcotton** [comment]
@dmitriim From what I can tell the guzzle library included in 4.2 has deprecated the const VERSION and replaced it with MAJOR_VERSION in lib/guzzlehttp/guzzle/src/ClientInterface.php so yes, the versions are different.
This fix forces local_aws to use its own library and not the Moodle one.

**Comment by dmitriim** [comment]
_> This fix forces local_aws to use its own library and not the Moodle one._

You mean opposite? Use Moodle one for 4.2+ ? Or am I missing something?

**Comment by sarahjcotton** [comment]
Yes that's correct - if the branch is 402 or greater then use the Moodle one, otherwise use the local_aws one.

**Comment by vlasov01** [comment]
Hi @sarahjcotton ,
Thank you for your fix. Could you please let me know when you think your fix will be merged?

**Comment by sarahjcotton** [comment]
I've changed this slightly so that if `$CFG->branch >= 402` it always uses the plugin library as opposed to checking whether the function exists first. Otherwise if the core library function has been loaded first it won't move onto the branch check.

**Review by mark-webster-catalyst — APPROVED** [review]
Confirmed this fixed local_aws in Moodle 4.2. @aspark21 can you confirm upgrade from 3.11 now works? (I was unable to reproduce the error, even before the updated patch)

Edit: Found an instance where upgrade fails. It still fails with the latest patch.

File: sdk/aws-autoloader.php [hunk 1]
```diff
@@ -2820,15 +2820,25 @@
...
-require __DIR__ . '/GuzzleHttp/functions_include.php';
-require __DIR__ . '/GuzzleHttp/Psr7/functions_include.php';
-require __DIR__ . '/GuzzleHttp/Promise/functions_include.php';
-require __DIR__ . '/JmesPath/JmesPath.php';
-require __DIR__ . '/Symfony/Polyfill/Intl/Idn/bootstrap.php';
+if (!function_exists('Aws\constantly')) {
+    require_once __DIR__ . '/Aws/functions.php';
+}
+
+if ($CFG->branch >= 402) {
```
Comment (mark-webster-catalyst) [inline sdk/aws-autoloader.php:2835]:
```suggestion
if ($CFG->branch >= 402 || file_exists($CFG->dirroot. '/lib/guzzlehttp/guzzle/src/functions_include.php')) {
```
Upgrading still fails because `$CFG->branch` is still the old value before core has upgraded. Suggest checking for existence of file as it is only in Moodle 4.2+, but leaving branch check in place for post-upgrade as it should be more efficient.

**Review by mark-webster-catalyst — CHANGES_REQUESTED** [review]

**Comment by mark-webster-catalyst** [comment]
I'm not sure why those checks failed, bug in the workflow?

**Comment by aspark21** [comment]
we’re using a forked version of this plugin in prod since it’s taken so long to get this fixed upstream (I’m assuming we’re the 4.3 client you were referring to) and we’re on a 4.2+ only version of the code with no version checks (the branch in #60)


Sorry for not having much time to re-test this but the upgrade steps that failed were for things that were updating files during the upgrade. e.g. format_grid was doing some conversions of icons

the code worked fine after the upgrade, it was just during the upgrade that it had problems.

**Comment by marxjohnson** [comment]
It's actually another site where we have this exact patch, and we're about to be upgrading some more, so hopefully we shouldn't see any further problems.
