### PR TITLE
Issue #61: Cleanup after unit test

### LINKED ISSUE #61: Unit tests failing in Totara 17
I have discovered that unit tests for local/aws are causing core unit tests to fail in Totara 17
```
There was 1 failure:

1) mod_approval_controller_form_delete_testcase::test_delete_with_form_in_use
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'Unsupported redirect detected, script execution terminated'
+'Section error!'

/var/www/t17/server/mod/approval/tests/controller_form_delete_test.php:130
/var/www/t17/server/lib/phpunit/classes/testcase.php:114
```

### PR DESCRIPTION
**Pull request by petersistrom**
Resolves #61

### CODE REVIEW

File: tests/admin_settings_aws_region_test.php [hunk 1]
```diff
@@ -36,6 +36,17 @@
  */
 class admin_settings_aws_region_test extends \advanced_testcase {
 
+    /**
+     * Cleanup after all tests are executed.
+     *
+     * @return void
+     */
+    public static function tearDownAfterClass(): void {
```
Comment (Peterburnett) [inline tests/admin_settings_aws_region_test.php:44]: Is there a reason this is in tearDownAfterClass() rather than just plain Teardown?
